# permissions for end users to view erpnextservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: erpnextserver-viewer-role
rules:
- apiGroups:
  - erpnext.com
  resources:
  - erpnextservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - erpnext.com
  resources:
  - erpnextservers/status
  verbs:
  - get
